### ISSUE TITLE
Request to upload pre-trained model

### ISSUE THREAD

**Issue by greenbrettmichael** [ChenyangLEI/sfp-wild#1]
Currently the combined datasets for sfp wild and the two comparison methods are uploaded which enables evaluation of the paper results after training.
Would you be willing to upload the results from training?
That would greatly reduce the effort needed to apply the model to out of sample data.

**Comment by ChenyangQiQi** [comment]
Thanks for suggestions. We have updated the README.
You may download the pretrained checkpoint from https://hkustconnect-my.sharepoint.com/:u:/g/personal/cqiaa_connect_ust_hk/EVo8OLJq0mRHtZoPXyUe8Q8BOawJF-EnvRDM3iG-ay7suw?e=99EyI4

**Comment by greenbrettmichael** [comment]
Thank you! I did end up training the model overnight at the default params in the replication bat and did not have any major issues.
