### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by MaksymTymkovych** [ChenyangLEI/sfp-wild#3]
Good day,

Thank you for your incredible work.

Could you please add the license files for the project itself, the dataset and the trained model.
After all, I need to know whether I can rely on the project, and with what restrictions.

Thank you!

**Comment by ChenyangLEI** [comment]
Added.

Thanks!

**Comment by MaksymTymkovych** [comment]
Thanks!

**Comment by MaksymTymkovych** [comment]
Have nice day!

Thanks!

пн, 28 лист. 2022 р. о 11:21 Chenyang LEI ***@***.***> пише:

**Comment by MaksymTymkovych** [comment]
close
